version: '3.8'
services:
  postgres:
    image: postgres:14-alpine
    container_name: pg_snowflake
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: petdb
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: